---
- hosts: all
  tasks:
  - name: Print Hello World
    debug:
      msg:
      - "Hello WOrld"
      - "Test Extra Var: '{{ extra_var_test }}'."
      - "Test Extra Var: '{{ morpheus['container']['name'] }}'."
