---
- name: Add a user
  hosts: all
  gather_facts: false
  tasks:
    - name: Add User
      win_user:
        name: pete
        password: "{{ lookup('cypher','secret=password/10/aapassword') }}"
        state: present
